debug: true

server:
  port: 8081

spring:
  application:
    name: plazoleta-service

  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 5672
    username: jonathan
    password: 12345

jwt:
  secret: "LONque1234567890LONque1234567890abcd"
